use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'COExtensions_Example' do
  pod 'COExtensions', :path => '../'

  target 'COExtensions_Tests' do
    inherit! :search_paths

    
  end
end
